backend:
  name: github
  repo: Mirar1103/NuxtHelloWorld

media_folder: static/img
public_folder: /img

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders

  # Required - a list of locales to show in the editor UI
  locales: [en, de, fr]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en

collections:
  - name: 'info'
    label: 'Info'
    folder: 'content/info'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    i18n:
      structure: multiple_folders
      locales: [en, de, fr]
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - { label: 'Header', name: 'header', widget: 'string', i18n: true }      
      - { label: 'Description', name: 'description', widget: 'string', i18n: true }
      - { label: 'Image', name: 'image', widget: 'string', i18n: true }

  - name: 'menu'
    label: 'Menu'
    folder: 'content/menu'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    i18n:
      structure: multiple_folders
      locales: [en, de, fr]
    editor:
      preview: false
    fields:
      - { label: 'Title1', name: 'title', widget: 'string', i18n: true }
      - label: 'Section1'
        name: 'section1'
        fields:
         - { label: 'Header1', name: 'header1', widget: 'string', i18n: true }      
         - { label: 'Description1', name: 'description1', widget: 'string', i18n: true }
         - { label: 'Header2', name: 'header2', widget: 'string', i18n: true }      
         - { label: 'Description2', name: 'description2', widget: 'string', i18n: true }
         - { label: 'Header3', name: 'header3', widget: 'string', i18n: true }      
         - { label: 'Description3', name: 'description3', widget: 'string', i18n: true }
         - { label: 'Header4', name: 'header4', widget: 'string', i18n: true }      
         - { label: 'Description4', name: 'description4', widget: 'string', i18n: true }
         - { label: 'Header5', name: 'header5', widget: 'string', i18n: true }      
         - { label: 'Description5', name: 'description5', widget: 'string', i18n: true }
         - { label: 'Header6', name: 'header6', widget: 'string', i18n: true }      
         - { label: 'Description6', name: 'description6', widget: 'string', i18n: true }
         - { label: 'Header7', name: 'header7', widget: 'string', i18n: true }      
         - { label: 'Description7', name: 'description7', widget: 'string', i18n: true }
         - { label: 'Header8', name: 'header8', widget: 'string', i18n: true }      
         - { label: 'Description8', name: 'description8', widget: 'string', i18n: true }
         - { label: 'Header9', name: 'header9', widget: 'string', i18n: true }      
         - { label: 'Description9', name: 'description9', widget: 'string', i18n: true }
         - { label: 'Header10', name: 'header10', widget: 'string', i18n: true }      
         - { label: 'Description10', name: 'description10', widget: 'string', i18n: true }
         - { label: 'Header11', name: 'header11', widget: 'string', i18n: true }      
         - { label: 'Description11', name: 'description11', widget: 'string', i18n: true }
