backend:
  name: github
  repo: Mirar1103/NuxtHelloWorld

media_folder: static/img
public_folder: /img

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders

  # Required - a list of locales to show in the editor UI
  locales: [en, de, es]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: de

collections:
  - label: 'Menu'
    name: 'menu'
    folder: 'content/menu'
    format: 'frontmatter'
    create: false
    slug: '{{slug}}'
    i18n:
      structure: multiple_folders
      locales: [en, de, es]
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - { label: 'Title1', name: 'title1', widget: 'string', i18n: true }
      - label: 'Section1'
        name: 'section1'
        widget: "object"
        i18n: true
        fields:
         - { label: 'Header1', name: 'header1', widget: 'string', i18n: true }      
         - { label: 'Description1', name: 'description1', widget: 'string', i18n: true }
         - { label: 'Header2', name: 'header2', widget: 'string', i18n: true }      
         - { label: 'Description2', name: 'description2', widget: 'string', i18n: true }
         - { label: 'Header3', name: 'header3', widget: 'string', i18n: true }      
         - { label: 'Description3', name: 'description3', widget: 'string', i18n: true }
         - { label: 'Header4', name: 'header4', widget: 'string', i18n: true }      
         - { label: 'Description4', name: 'description4', widget: 'string', i18n: true }
         - { label: 'Header5', name: 'header5', widget: 'string', i18n: true }      
         - { label: 'Description5', name: 'description5', widget: 'string', i18n: true }
         - { label: 'Header6', name: 'header6', widget: 'string', i18n: true }      
         - { label: 'Description6', name: 'description6', widget: 'string', i18n: true }
         - { label: 'Header7', name: 'header7', widget: 'string', i18n: true }      
         - { label: 'Description7', name: 'description7', widget: 'string', i18n: true }
         - { label: 'Header8', name: 'header8', widget: 'string', i18n: true }      
         - { label: 'Description8', name: 'description8', widget: 'string', i18n: true }
         - { label: 'Header9', name: 'header9', widget: 'string', i18n: true }      
         - { label: 'Description9', name: 'description9', widget: 'string', i18n: true }
         - { label: 'Header10', name: 'header10', widget: 'string', i18n: true }      
         - { label: 'Description10', name: 'description10', widget: 'string', i18n: true }
         - { label: 'Header11', name: 'header11', widget: 'string', i18n: true }      
         - { label: 'Description11', name: 'description11', widget: 'string', i18n: true }
      - { label: 'Title2', name: 'title2', widget: 'string', i18n: true }
      - label: 'Section2'
        name: 'section2'
        widget: "object"
        i18n: true
        fields:
         - { label: 'Header1', name: 'header1', widget: 'string', i18n: true }      
         - { label: 'Description1', name: 'description1', widget: 'string', i18n: true }
         - { label: 'Header2', name: 'header2', widget: 'string', i18n: true }      
         - { label: 'Description2', name: 'description2', widget: 'string', i18n: true }
         - { label: 'Header3', name: 'header3', widget: 'string', i18n: true }      
         - { label: 'Description3', name: 'description3', widget: 'string', i18n: true }
         - { label: 'Header4', name: 'header4', widget: 'string', i18n: true }      
         - { label: 'Description4', name: 'description4', widget: 'string', i18n: true }
         - { label: 'Header5', name: 'header5', widget: 'string', i18n: true }      
         - { label: 'Description5', name: 'description5', widget: 'string', i18n: true }
         - { label: 'Header6', name: 'header6', widget: 'string', i18n: true }      
         - { label: 'Description6', name: 'description6', widget: 'string', i18n: true }
         - { label: 'Header7', name: 'header7', widget: 'string', i18n: true }      
         - { label: 'Description7', name: 'description7', widget: 'string', i18n: true }
         - { label: 'Header8', name: 'header8', widget: 'string', i18n: true }      
         - { label: 'Description8', name: 'description8', widget: 'string', i18n: true }
         - { label: 'Header9', name: 'header9', widget: 'string', i18n: true }      
         - { label: 'Description9', name: 'description9', widget: 'string', i18n: true }
         - { label: 'Header10', name: 'header10', widget: 'string', i18n: true }      
         - { label: 'Description10', name: 'description10', widget: 'string', i18n: true }
         - { label: 'Header11', name: 'header11', widget: 'string', i18n: true }      
         - { label: 'Description11', name: 'description11', widget: 'string', i18n: true }
  - label: 'Footer'
    name: 'footer'
    folder: 'content/footer'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    i18n:
      structure: multiple_folders
      locales: [en, de, es]
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - label: 'Column1'
        name: 'column1'
        widget: "object"
        i18n: true
        fields: 
         - label: 'Section1'
           name: 'section1'
           widget: "object"
           i18n: true
           fields:
            - { label: 'Header', name: 'header', widget: 'string', i18n: true } 
            - { label: 'Name1', name: 'name1', widget: 'string', i18n: true }
            - { label: 'Link1', name: 'link1', widget: 'string', i18n: true }
            - { label: 'Name2', name: 'name2', widget: 'string', i18n: true }
            - { label: 'Link2', name: 'link2', widget: 'string', i18n: true } 
         - label: 'Section2'
           name: 'section2'
           widget: "object"
           i18n: true
           fields:
            - { label: 'Header', name: 'header', widget: 'string', i18n: true } 
            - { label: 'Name1', name: 'name1', widget: 'string', i18n: true }
            - { label: 'Link1', name: 'link1', widget: 'string', i18n: true }
            - { label: 'Name2', name: 'name2', widget: 'string', i18n: true }
            - { label: 'Link2', name: 'link2', widget: 'string', i18n: true }
            - { label: 'Name3', name: 'name3', widget: 'string', i18n: true }
            - { label: 'Link3', name: 'link3', widget: 'string', i18n: true }
      - label: 'Column2'
        name: 'column2'
        widget: "object"
        i18n: true
        fields:
        - { label: 'Header', name: 'header', widget: 'string', i18n: true } 
        - { label: 'Name1', name: 'name1', widget: 'string', i18n: true }
        - { label: 'Link1', name: 'link1', widget: 'string', i18n: true }
        - { label: 'Name2', name: 'name2', widget: 'string', i18n: true }
        - { label: 'Link2', name: 'link2', widget: 'string', i18n: true }
        - { label: 'Name3', name: 'name3', widget: 'string', i18n: true }
        - { label: 'Link3', name: 'link3', widget: 'string', i18n: true } 
        - { label: 'Name4', name: 'name4', widget: 'string', i18n: true }
        - { label: 'Link4', name: 'link4', widget: 'string', i18n: true }
        - { label: 'Name5', name: 'name5', widget: 'string', i18n: true }
        - { label: 'Link5', name: 'link5', widget: 'string', i18n: true }
        - { label: 'Name6', name: 'name6', widget: 'string', i18n: true }
        - { label: 'Link6', name: 'link6', widget: 'string', i18n: true } 
        - { label: 'Name7', name: 'name7', widget: 'string', i18n: true }
        - { label: 'Link7', name: 'link7', widget: 'string', i18n: true }
        - { label: 'Name8', name: 'name8', widget: 'string', i18n: true }
        - { label: 'Link8', name: 'link8', widget: 'string', i18n: true }
        - { label: 'Name9', name: 'name9', widget: 'string', i18n: true }
        - { label: 'Link9', name: 'link9', widget: 'string', i18n: true } 
        - { label: 'Name10', name: 'name10', widget: 'string', i18n: true }
        - { label: 'Link10', name: 'link10', widget: 'string', i18n: true }
        - { label: 'Name11', name: 'name11', widget: 'string', i18n: true }
        - { label: 'Link11', name: 'link11', widget: 'string', i18n: true }
        - { label: 'Name12', name: 'name12', widget: 'string', i18n: true }
        - { label: 'Link12', name: 'link12', widget: 'string', i18n: true }
        - { label: 'Name13', name: 'name13', widget: 'string', i18n: true }
        - { label: 'Link13', name: 'link13', widget: 'string', i18n: true }
      - label: 'Column3'
        name: 'column3'
        widget: "object"
        i18n: true
        fields: 
         - label: 'Section1'
           name: 'section1'
           widget: "object"
           i18n: true
           fields:
            - { label: 'Header', name: 'header', widget: 'string', i18n: true } 
            - { label: 'Name1', name: 'name1', widget: 'string', i18n: true }
            - { label: 'Link1', name: 'link1', widget: 'string', i18n: true }
            - { label: 'Name2', name: 'name2', widget: 'string', i18n: true }
            - { label: 'Link2', name: 'link2', widget: 'string', i18n: true }
            - { label: 'Name3', name: 'name3', widget: 'string', i18n: true }
            - { label: 'Link3', name: 'link3', widget: 'string', i18n: true }
            - { label: 'Name4', name: 'name4', widget: 'string', i18n: true }
            - { label: 'Link4', name: 'link4', widget: 'string', i18n: true }
            - { label: 'Name5', name: 'name5', widget: 'string', i18n: true }
            - { label: 'Link5', name: 'link5', widget: 'string', i18n: true }
            - { label: 'Name6', name: 'name6', widget: 'string', i18n: true }
            - { label: 'Link6', name: 'link6', widget: 'string', i18n: true } 
         - label: 'Section2'
           name: 'section2'
           widget: "object"
           i18n: true
           fields:
            - { label: 'Header', name: 'header', widget: 'string', i18n: true } 
            - { label: 'ContactTimes', name: 'contactTimes', widget: 'string', i18n: true }
            - { label: 'Number', name: 'number', widget: 'string', i18n: true }
            - { label: 'NumberHref', name: 'numberHref', widget: 'string', i18n: true }
            - { label: 'Mail', name: 'mail', widget: 'string', i18n: true }
            - { label: 'MailHref', name: 'mailHref', widget: 'string', i18n: true }
         - label: 'Section3'
           name: 'section3'
           widget: "object"
           i18n: true
           fields:
            - { label: 'Header', name: 'header', widget: 'string', i18n: true } 
            - { label: 'Name1', name: 'name1', widget: 'string', i18n: true }
            - { label: 'Link1', name: 'link1', widget: 'string', i18n: true }
            - { label: 'Name2', name: 'name2', widget: 'string', i18n: true }
            - { label: 'Link2', name: 'link2', widget: 'string', i18n: true } 
  - label: 'CIB coSys'
    name: 'mockPage'
    folder: 'content/mockPage'
    format: 'frontmatter'
    create: false
    slug: '{{slug}}'
    i18n:
      structure: multiple_folders
      locales: [en, de, es]
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - { label: 'Name', name: 'name', widget: 'string', i18n: true }
      - label: 'CustomComponent1'
        name: 'customComponent1'
        widget: "object"
        i18n: true
        fields:
         - { label: 'TitleBold', name: 'titleBold', widget: 'string', i18n: true }      
         - { label: 'Subtitle', name: 'subtitle', widget: 'string', i18n: true }
         - { label: 'Description', name: 'description', widget: 'string', i18n: true }      
         - { label: 'ListElement1', name: 'listElement1', widget: 'string', i18n: true }
         - { label: 'ListElement2', name: 'listElement2', widget: 'string', i18n: true }      
         - { label: 'ListElement3', name: 'listElement3', widget: 'string', i18n: true }
         - { label: 'ListElement4', name: 'listElement4', widget: 'string', i18n: true }
         - { label: 'Image', name: 'image', widget: 'image', i18n: true }      
         - { label: 'Button', name: 'Button', widget: 'string', i18n: true }
         - { label: 'ButtonLink', name: 'buttonLink', widget: 'string', i18n: true }
      - label: 'GridImageTop1'
        name: 'gridImageTop1'
        widget: "object"
        i18n: true
        fields:
         - { label: 'Title', name: 'title', widget: 'string', i18n: true }      
         - { label: 'Image1', name: 'image1', widget: 'image', i18n: true }
         - { label: 'Header1', name: 'header1', widget: 'string', i18n: true }      
         - { label: 'Description1', name: 'description1', widget: 'string', i18n: true }     
         - { label: 'Image2', name: 'image2', widget: 'image', i18n: true }
         - { label: 'Header2', name: 'header2', widget: 'string', i18n: true }      
         - { label: 'Description2', name: 'description2', widget: 'string', i18n: true }     
         - { label: 'Image3', name: 'image3', widget: 'image', i18n: true }
         - { label: 'Header3', name: 'header3', widget: 'string', i18n: true }      
         - { label: 'Description3', name: 'description3', widget: 'string', i18n: true }     
         - { label: 'Image4', name: 'image4', widget: 'image', i18n: true }
         - { label: 'Header4', name: 'header4', widget: 'string', i18n: true }      
         - { label: 'Description4', name: 'description4', widget: 'string', i18n: true }     
         - { label: 'Image5', name: 'image5', widget: 'image', i18n: true }
         - { label: 'Header5', name: 'header5', widget: 'string', i18n: true }      
         - { label: 'Description5', name: 'description5', widget: 'string', i18n: true }     
         - { label: 'Image6', name: 'image6', widget: 'image', i18n: true }
         - { label: 'Header6', name: 'header6', widget: 'string', i18n: true }      
         - { label: 'Description6', name: 'description6', widget: 'string', i18n: true }     
         - { label: 'Image7', name: 'image7', widget: 'image', i18n: true }
         - { label: 'Header7', name: 'header7', widget: 'string', i18n: true }      
         - { label: 'Description7', name: 'description7', widget: 'string', i18n: true }     
         - { label: 'Image8', name: 'image8', widget: 'image', i18n: true }
         - { label: 'Header8', name: 'header8', widget: 'string', i18n: true }      
         - { label: 'Description8', name: 'description8', widget: 'string', i18n: true }
          

